<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view_address',
            'view_any_address',
            'create_address',
            'update_address',
            'restore_address',
            'restore_any_address',
            'replicate_address',
            'reorder_address',
            'delete_address',
            'delete_any_address',
            'force_delete_address',
            'force_delete_any_address',
            'view_customer',
            'view_any_customer',
            'create_customer',
            'update_customer',
            'restore_customer',
            'restore_any_customer',
            'replicate_customer',
            'reorder_customer',
            'delete_customer',
            'delete_any_customer',
            'force_delete_customer',
            'force_delete_any_customer',
            'view_driver',
            'view_any_driver',
            'create_driver',
            'update_driver',
            'restore_driver',
            'restore_any_driver',
            'replicate_driver',
            'reorder_driver',
            'delete_driver',
            'delete_any_driver',
            'force_delete_driver',
            'force_delete_any_driver',
            'view_order',
            'view_any_order',
            'create_order',
            'update_order',
            'restore_order',
            'restore_any_order',
            'replicate_order',
            'reorder_order',
            'delete_order',
            'delete_any_order',
            'force_delete_order',
            'force_delete_any_order',
            'view_property',
            'view_any_property',
            'create_property',
            'update_property',
            'restore_property',
            'restore_any_property',
            'replicate_property',
            'reorder_property',
            'delete_property',
            'delete_any_property',
            'force_delete_property',
            'force_delete_any_property',
            'view_role',
            'view_any_role',
            'create_role',
            'update_role',
            'delete_role',
            'delete_any_role',
            'view_service',
            'view_any_service',
            'create_service',
            'update_service',
            'restore_service',
            'restore_any_service',
            'replicate_service',
            'reorder_service',
            'delete_service',
            'delete_any_service',
            'force_delete_service',
            'force_delete_any_service',
            'view_service::item',
            'view_any_service::item',
            'create_service::item',
            'update_service::item',
            'restore_service::item',
            'restore_any_service::item',
            'replicate_service::item',
            'reorder_service::item',
            'delete_service::item',
            'delete_any_service::item',
            'force_delete_service::item',
            'force_delete_any_service::item',
            'view_sms',
            'view_any_sms',
            'create_sms',
            'update_sms',
            'restore_sms',
            'restore_any_sms',
            'replicate_sms',
            'reorder_sms',
            'delete_sms',
            'delete_any_sms',
            'force_delete_sms',
            'force_delete_any_sms',
            'view_user',
            'view_any_user',
            'create_user',
            'update_user',
            'restore_user',
            'restore_any_user',
            'replicate_user',
            'reorder_user',
            'delete_user',
            'delete_any_user',
            'force_delete_user',
            'force_delete_any_user',
            'widget_OverlookWidget',
            'page_SystemManager',
        ];

        foreach ($permissions as $value) {
            Permission::Create([
                'name' => $value,
                'guard_name' => "web"
            ]);
        }
    }
}
